
package Viwe;

import Controler.Main;
import Model.Serialização;
import Model.Simulador;
import java.util.HashMap;
import javax.swing.ImageIcon;

public class Tela_executaRodada extends javax.swing.JPanel {
    Serialização obj;
    int jogosRodada = 5;
    int[][] tabelaJogos;
    int[][] tabelaResults;
    ImageIcon[] vetorImagens;
    Simulador s1;
    
    public Tela_executaRodada(Serialização obj) {
        initComponents();
        this.obj = obj;
        this.tabelaJogos = obj.getTabelaJogos();
        this.tabelaResults = obj.getResultados();
        this.s1 = s1;
        iniciaLb_Times();
        iniciaLb_logos();
        
    }
    
    public void iniciaLb_Times(){
        lb_titulo.setText("Rodada " + String.valueOf(obj.getRodada()+1));
        int jogoAtual = (obj.getRodada()) * jogosRodada;
            lb_time1.setText(obj.getListaTime().get(tabelaJogos[jogoAtual][0]).getNome());
            lb_time2.setText(obj.getListaTime().get(tabelaJogos[jogoAtual][1]).getNome());
            lb_time3.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+1][0]).getNome());
            lb_time4.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+1][1]).getNome());
            lb_time5.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+2][0]).getNome());
            lb_time6.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+2][1]).getNome());
            lb_time7.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+3][0]).getNome());
            lb_time8.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+3][1]).getNome());
            lb_time9.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+4][0]).getNome());
            lb_time10.setText(obj.getListaTime().get(tabelaJogos[jogoAtual+4][1]).getNome());
    }
    
    
    public void inicializaVetorImagens(){
        ImageIcon i0 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/saoPaulo_30x30.png"));
        ImageIcon i1 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/santos_30x30.png"));
        ImageIcon i2 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/palmeiras_30x30.png"));
        ImageIcon i3 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/corinthias_30x30.png"));
        ImageIcon i4 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/flamengo_30x30.png"));
        ImageIcon i5 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/fluminense_30x30.png"));
        ImageIcon i6 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/botafogo_30x30.png"));
        ImageIcon i7 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/cruzeiro_30x30.png"));
        ImageIcon i8 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/atleticoMineiro_30x30.png"));
        ImageIcon i9 = new ImageIcon(getClass().getResource("/imagens_escudos_times_30x30/bahia_30x30.png"));
       
        vetorImagens = new ImageIcon[10];
        vetorImagens[0] = i0;
        vetorImagens[1] = i1;
        vetorImagens[2] = i2;
        vetorImagens[3] = i3;
        vetorImagens[4] = i4;
        vetorImagens[5] = i5;
        vetorImagens[6] = i6;
        vetorImagens[7] = i7;
        vetorImagens[8] = i8;
        vetorImagens[9] = i9;
    }
    
    public void iniciaLb_logos(){
        inicializaVetorImagens();
        
        int jogoAtual = obj.getRodada() * jogosRodada;
        lb_logo1.setIcon(vetorImagens[tabelaJogos[jogoAtual][0]]);
        lb_logo2.setIcon(vetorImagens[tabelaJogos[jogoAtual][1]]);
        lb_logo3.setIcon(vetorImagens[tabelaJogos[jogoAtual+1][0]]);
        lb_logo4.setIcon(vetorImagens[tabelaJogos[jogoAtual+1][1]]);
        lb_logo5.setIcon(vetorImagens[tabelaJogos[jogoAtual+2][0]]);
        lb_logo6.setIcon(vetorImagens[tabelaJogos[jogoAtual+2][1]]);
        lb_logo7.setIcon(vetorImagens[tabelaJogos[jogoAtual+3][0]]);
        lb_logo8.setIcon(vetorImagens[tabelaJogos[jogoAtual+3][1]]);
        lb_logo9.setIcon(vetorImagens[tabelaJogos[jogoAtual+4][0]]);
        lb_logo10.setIcon(vetorImagens[tabelaJogos[jogoAtual+4][1]]);

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lb_titulo = new javax.swing.JLabel();
        bt_executarRodada = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        bt_mostrarJogos = new javax.swing.JButton();
        bt_classificacao = new javax.swing.JButton();
        lb_logo2 = new javax.swing.JLabel();
        lb_logo4 = new javax.swing.JLabel();
        lb_logo6 = new javax.swing.JLabel();
        lb_logo8 = new javax.swing.JLabel();
        lb_logo10 = new javax.swing.JLabel();
        lb_time6 = new javax.swing.JLabel();
        lb_time8 = new javax.swing.JLabel();
        lb_time10 = new javax.swing.JLabel();
        lb_time2 = new javax.swing.JLabel();
        lb_time4 = new javax.swing.JLabel();
        lb_result1 = new javax.swing.JLabel();
        lb_result2 = new javax.swing.JLabel();
        lb_result3 = new javax.swing.JLabel();
        lb_result4 = new javax.swing.JLabel();
        lb_result5 = new javax.swing.JLabel();
        lb_logo3 = new javax.swing.JLabel();
        lb_logo5 = new javax.swing.JLabel();
        lb_logo9 = new javax.swing.JLabel();
        lb_time7 = new javax.swing.JLabel();
        lb_time9 = new javax.swing.JLabel();
        lb_time1 = new javax.swing.JLabel();
        lb_time3 = new javax.swing.JLabel();
        lb_time5 = new javax.swing.JLabel();
        lb_logo1 = new javax.swing.JLabel();
        lb_logo7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(632, 440));
        setLayout(null);

        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Rodada <x>");
        add(lb_titulo);
        lb_titulo.setBounds(245, 22, 147, 22);

        bt_executarRodada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_executarRodada.setForeground(new java.awt.Color(0, 0, 0));
        bt_executarRodada.setText("Executar a Rodada");
        bt_executarRodada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_executarRodadaMouseClicked(evt);
            }
        });
        add(bt_executarRodada);
        bt_executarRodada.setBounds(210, 250, 187, 33);

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_voltar.setForeground(new java.awt.Color(0, 0, 0));
        bt_voltar.setText("Voltar");
        bt_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_voltarMouseClicked(evt);
            }
        });
        add(bt_voltar);
        bt_voltar.setBounds(210, 380, 187, 33);

        bt_mostrarJogos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_mostrarJogos.setForeground(new java.awt.Color(0, 0, 0));
        bt_mostrarJogos.setText("Mostrar Jogos");
        bt_mostrarJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mostrarJogosMouseClicked(evt);
            }
        });
        add(bt_mostrarJogos);
        bt_mostrarJogos.setBounds(210, 290, 187, 33);

        bt_classificacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_classificacao.setForeground(new java.awt.Color(0, 0, 0));
        bt_classificacao.setText("Classificação");
        bt_classificacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_classificacaoMouseClicked(evt);
            }
        });
        bt_classificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_classificacaoActionPerformed(evt);
            }
        });
        add(bt_classificacao);
        bt_classificacao.setBounds(210, 330, 187, 33);

        lb_logo2.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo2.setText("jLabel11");
        add(lb_logo2);
        lb_logo2.setBounds(580, 70, 30, 30);

        lb_logo4.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo4.setText("jLabel12");
        add(lb_logo4);
        lb_logo4.setBounds(580, 100, 30, 30);

        lb_logo6.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo6.setText("jLabel13");
        add(lb_logo6);
        lb_logo6.setBounds(580, 130, 30, 30);

        lb_logo8.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo8.setText("jLabel14");
        add(lb_logo8);
        lb_logo8.setBounds(580, 160, 30, 30);

        lb_logo10.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo10.setText("jLabel15");
        add(lb_logo10);
        lb_logo10.setBounds(580, 190, 30, 30);

        lb_time6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time6.setForeground(new java.awt.Color(255, 255, 255));
        lb_time6.setText("Time6");
        add(lb_time6);
        lb_time6.setBounds(420, 130, 151, 25);

        lb_time8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time8.setForeground(new java.awt.Color(255, 255, 255));
        lb_time8.setText("Time8");
        add(lb_time8);
        lb_time8.setBounds(420, 160, 151, 25);

        lb_time10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time10.setForeground(new java.awt.Color(255, 255, 255));
        lb_time10.setText("Time10");
        add(lb_time10);
        lb_time10.setBounds(420, 190, 151, 25);

        lb_time2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time2.setForeground(new java.awt.Color(255, 255, 255));
        lb_time2.setText("Time2");
        add(lb_time2);
        lb_time2.setBounds(420, 70, 150, 25);

        lb_time4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time4.setForeground(new java.awt.Color(255, 255, 255));
        lb_time4.setText("Time4");
        add(lb_time4);
        lb_time4.setBounds(420, 100, 151, 25);

        lb_result1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_result1.setForeground(new java.awt.Color(255, 255, 255));
        lb_result1.setText("x");
        add(lb_result1);
        lb_result1.setBounds(290, 80, 10, 20);

        lb_result2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_result2.setForeground(new java.awt.Color(255, 255, 255));
        lb_result2.setText("x");
        add(lb_result2);
        lb_result2.setBounds(290, 110, 10, 20);

        lb_result3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_result3.setForeground(new java.awt.Color(255, 255, 255));
        lb_result3.setText("x");
        add(lb_result3);
        lb_result3.setBounds(290, 140, 10, 20);

        lb_result4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_result4.setForeground(new java.awt.Color(255, 255, 255));
        lb_result4.setText("x");
        add(lb_result4);
        lb_result4.setBounds(290, 160, 10, 25);

        lb_result5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_result5.setForeground(new java.awt.Color(255, 255, 255));
        lb_result5.setText("x");
        add(lb_result5);
        lb_result5.setBounds(290, 190, 10, 25);

        lb_logo3.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo3.setText("jLabel7");
        add(lb_logo3);
        lb_logo3.setBounds(30, 100, 30, 30);

        lb_logo5.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo5.setText("jLabel8");
        add(lb_logo5);
        lb_logo5.setBounds(30, 130, 30, 30);

        lb_logo9.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo9.setText("jLabel10");
        add(lb_logo9);
        lb_logo9.setBounds(30, 190, 30, 30);

        lb_time7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time7.setForeground(new java.awt.Color(255, 255, 255));
        lb_time7.setText("Time7");
        add(lb_time7);
        lb_time7.setBounds(80, 160, 156, 25);

        lb_time9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time9.setForeground(new java.awt.Color(255, 255, 255));
        lb_time9.setText("Time9");
        add(lb_time9);
        lb_time9.setBounds(80, 190, 156, 25);

        lb_time1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time1.setForeground(new java.awt.Color(255, 255, 255));
        lb_time1.setText("Time1");
        add(lb_time1);
        lb_time1.setBounds(80, 70, 150, 25);

        lb_time3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time3.setForeground(new java.awt.Color(255, 255, 255));
        lb_time3.setText("TIme3");
        add(lb_time3);
        lb_time3.setBounds(80, 100, 150, 25);

        lb_time5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_time5.setForeground(new java.awt.Color(255, 255, 255));
        lb_time5.setText("Time5");
        add(lb_time5);
        lb_time5.setBounds(80, 130, 150, 25);

        lb_logo1.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo1.setText("jLabel6");
        add(lb_logo1);
        lb_logo1.setBounds(30, 70, 30, 30);

        lb_logo7.setForeground(new java.awt.Color(255, 255, 255));
        lb_logo7.setText("jLabel1");
        add(lb_logo7);
        lb_logo7.setBounds(30, 160, 30, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo estadio_executaRodada.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_executarRodadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_executarRodadaMouseClicked
        Main.c1.getControlerExecutaRodada().executarRodadaMouseClicked();
    }//GEN-LAST:event_bt_executarRodadaMouseClicked

    private void bt_classificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_classificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_classificacaoActionPerformed

    private void bt_classificacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_classificacaoMouseClicked
        Main.c1.getControlerExecutaRodada().bt_classificacaoMouseCliecked();
    }//GEN-LAST:event_bt_classificacaoMouseClicked

    private void bt_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_voltarMouseClicked
        Main.c1.getControlerExecutaRodada().bt_voltarMouseClicked();
    }//GEN-LAST:event_bt_voltarMouseClicked

    private void bt_mostrarJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mostrarJogosMouseClicked
       Main.c1.getControlerExecutaRodada().mostrarJogosMouseClicked();
    }//GEN-LAST:event_bt_mostrarJogosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_classificacao;
    private javax.swing.JButton bt_executarRodada;
    private javax.swing.JButton bt_mostrarJogos;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_logo1;
    private javax.swing.JLabel lb_logo10;
    private javax.swing.JLabel lb_logo2;
    private javax.swing.JLabel lb_logo3;
    private javax.swing.JLabel lb_logo4;
    private javax.swing.JLabel lb_logo5;
    private javax.swing.JLabel lb_logo6;
    private javax.swing.JLabel lb_logo7;
    private javax.swing.JLabel lb_logo8;
    private javax.swing.JLabel lb_logo9;
    private javax.swing.JLabel lb_result1;
    private javax.swing.JLabel lb_result2;
    private javax.swing.JLabel lb_result3;
    private javax.swing.JLabel lb_result4;
    private javax.swing.JLabel lb_result5;
    private javax.swing.JLabel lb_time1;
    private javax.swing.JLabel lb_time10;
    private javax.swing.JLabel lb_time2;
    private javax.swing.JLabel lb_time3;
    private javax.swing.JLabel lb_time4;
    private javax.swing.JLabel lb_time5;
    private javax.swing.JLabel lb_time6;
    private javax.swing.JLabel lb_time7;
    private javax.swing.JLabel lb_time8;
    private javax.swing.JLabel lb_time9;
    private javax.swing.JLabel lb_titulo;
    // End of variables declaration//GEN-END:variables
}
